# Generated by Django 5.1.3 on 2025-06-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoadAnomalyInferenceRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
