# Generated by Django 5.1.3 on 2025-05-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoadAnomalyManualDataCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.BigIntegerField()),
                ("acc_x", models.FloatField()),
                ("acc_y", models.FloatField()),
                ("acc_z", models.FloatField()),
                ("rot_x", models.FloatField()),
                ("rot_y", models.FloatField()),
                ("rot_z", models.FloatField()),
                ("speed", models.FloatField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("accuracy", models.FloatField()),
                ("timestamp", models.TextField()),
                ("log_interval", models.BigIntegerField()),
                ("anomaly", models.TextField()),
            ],
        ),
    ]
