# Generated by Django 5.1.3 on 2025-05-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoadAnomalyInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anomaly",
                    models.CharField(
                        choices=[
                            ("no_defect", "No-Defect Segment"),
                            ("low_crack", "Low-Crack Segment"),
                            ("low_pothole", "Low-Pothole Segment"),
                            ("high_crack", "High-Crack Segment"),
                            ("high_pothole", "High-Pothole Segment"),
                        ],
                        default="no_defect",
                        help_text="Classify the road anomaly based on severity.",
                        max_length=20,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
