# Generated by Django 5.1.3 on 2025-05-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RoadAnomalyInput", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadanomalyinput",
            name="anomaly",
            field=models.CharField(
                choices=[
                    ("smooth", "Smooth Segment"),
                    ("crack", "Crack Segment"),
                    ("bump", "Bump Segment"),
                    ("road-patch", "Road Patch Segment"),
                    ("pothole_mild", "Mild Pothole Segment"),
                    ("pothole_severe", "Severe Pothole Segment"),
                ],
                default="no_defect",
                help_text="Classify the road anomaly based on severity.",
                max_length=20,
            ),
        ),
    ]
