# Generated by Django 5.1.3 on 2025-05-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RoadAnomalyInput", "0002_alter_roadanomalyinput_anomaly"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadanomalyinput",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
