# Generated by Django 5.1.3 on 2025-05-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RoadAnomalyInput", "0003_alter_roadanomalyinput_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadanomalyinput",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
