# Generated by Django 5.1.3 on 2025-06-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RoadAnomalyPredictionOutput", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadanomalypredictionoutput",
            name="acc_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roadanomalypredictionoutput",
            name="acc_y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roadanomalypredictionoutput",
            name="acc_z",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roadanomalypredictionoutput",
            name="accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roadanomalypredictionoutput",
            name="batch_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roadanomalypredictionoutput",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roadanomalypredictionoutput",
            name="log_interval",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roadanomalypredictionoutput",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roadanomalypredictionoutput",
            name="rot_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roadanomalypredictionoutput",
            name="rot_y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roadanomalypredictionoutput",
            name="rot_z",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roadanomalypredictionoutput",
            name="speed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
